[build]
  publish = "."

[[redirects]]
  from = "/produkt/*"
  to = "/produkt/index.html"
  status = 200

[[redirects]]
  from = "/mattor/*"
  to = "/mattor/index.html"
  status = 200

[[redirects]]
  from = "/metervara/*"
  to = "/metervara/index.html"
  status = 200

[[redirects]]
  from = "/gangmattor/*"
  to = "/gangmattor/index.html"
  status = 200

[[redirects]]
  from = "/runda-mattor/*"
  to = "/runda-mattor/index.html"
  status = 200

[[redirects]]
  from = "/badrumsmattor/*"
  to = "/badrumsmattor/index.html"
  status = 200

[[redirects]]
  from = "/gardiner/*"
  to = "/gardiner/index.html"
  status = 200

[[redirects]]
  from = "/rea/*"
  to = "/rea/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
